services:
  postgres:
    image: postgres:16-alpine
    container_name: smart-tourism-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: smart_tourism_lbs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - smart-tourism-postgres-data:/var/lib/postgresql/data

volumes:
  smart-tourism-postgres-data:
